
language: haskell

# Install yarn since we need it to install tsc
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

ghc:
  - "7.10"
  - "7.8"
  - "7.6"

install:
  - cd test_assets && yarn install
  - stack install

script:
  - stack test
